# Generated by Django 4.2.5 on 2023-09-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='project-one', max_length=100),
            preserve_default=False,
        ),
    ]
